version: '3.8'
services:
    app:
        container_name: myfirst_dockerized_rest_server
        build:
            dockerfile: rest_api/Dockerfile
            context: .
        depends_on:
            db
        ports:
            "8000:80"
        volumes:
            - ./rest_api:/var/www/html

    db:
        container_name: myfirst_dockerized_database_server
        image: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            "3306:3306"
        volumes:
            - ./db_dumps/world.sql:/docker-entrypointinitdb.d/world.sql